---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <NAMESPACE>
resources:
  - ../../base
  - virtual-service.yaml
  - hpa-api.yaml
images:
  - name: <IMAGE_NAME>
    newName: <IMAGE_FQDN>
    newTag: <GIT COMMIT HASH>
